### PR TITLE
Make the sidebar section labels more obvious

### PR DESCRIPTION
**Pull request by jstasiak**
Following the principles of The Grand Unified Theory of Documentation[1] and the conversation we had on the documention defficiencies[2] I thought I'd go ahead and change the labels a little bit to make it (more) clear what they are.

I haven't changed the directory names yet to avoid moving files around and changing files' contents in the same commit.

[1] https://documentation.divio.com/
[2] https://linear.app/lune/issue/LUN-2365/docs-review

### CODE REVIEW

**Comment by jstasiak** [comment]
FWIW the "integration guides" -> "how-to guides" change is something I'm on the fence about and ready to be talked out of it.

**Comment by jstasiak** [comment]
Also: the labels are to be discussed, this is just a proposal

**Comment by rbruggem** [comment]
I'm not convinced about 'Key Topics'.

I agree that we need something better, but I'm not convinced about 'Key Topics'.

**Comment by raguiar9080** [comment]
I think the main issue we have right now is that we have API information and Key topics mixed together. They should be separate and probably on different levels. Things like `Order lifecycle`, `Webhooks`,`Client Accounts` etc. are concepts that help understand the business and how we work. `Authentication`, `Pagination`, `Required and nullable properties` are related to using the API itself. So we should have the integration guides (base level), Key topics (base level) and Lune API (I would say inside API reference?)

Regarding the labels for these:
- I like `How-to guides` but I wasn't against `Integration guides`. Honestly can't say I have much of a preference, but I do think `how-to` might be clearer?
- For Lune API information, I like `Lune API` but not really attached to it. `Using the API` might work.
- Key concepts is probably my favourite, but I think all of the alternatives present here work.

**Comment by jstasiak** [comment]
> `Authentication`, `Pagination`, `Required and nullable properties` are related to using the API itself.

I mean everything here is related to using the API so that's fine. I guess the question is: are these aimed at informing about things or making people understand things better. It's probably a mix.

**Comment by jstasiak** [comment]
We've had some time to think about this, I'd say let's revisit the PR.

I'm not attached to the names in the change as long as we ship *something* to improve the status quo.

**Review by raguiar9080 — APPROVED** [review]
After reopening the preview branch now, I like it 👍 I think `Key Topics` and `API Reference` is much easier to understand than the previous status quo. `How-to` vs `Integration` I don't feel particularly attached to either so I'm fine with both.

Just one question, do we want to change the urls? `Key topics` being under `api` on the url is a bit weird 🤔 I'm unsure how valuable are current stored urls for customers, worst case I'm sure we can make it redirect and keep backwards compatibility. Another PR thought 👍

**Comment by jstasiak** [comment]
I forgot about the URL-s, I'll fix that

**Comment by rbruggem** [comment]
Could we keep this on hold for a little more?
There is a ticket in the new Documentation project addressing this.
I'd like to organise a few things first.

**Comment by jstasiak** [comment]
Sure, I'm in no rush to merge this, just don't want it forgotten. Do you want to close this and come back to it when appropriate?

**Comment by rbruggem** [comment]
> Sure, I'm in no rush to merge this, just don't want it forgotten. Do you want to close this and come back to it when appropriate?

Let's do this.

**Comment by rbruggem** [comment]
Didn't mean to merge

**Comment by rbruggem** [comment]
https://github.com/lune-climate/lune-docs/pull/341

**Pull request merged**
