### PR TITLE
Upgrade to modern Yarn (meaning 4.4.0 today)

### PR DESCRIPTION
**Pull request by jstasiak**
On top of just keeping things up to date it seems like it performs some dependency management operations much faster (judging by my interactions with it).

There are some nice advantages advertised here [1].

I followed this procedure:

1. yarn set version stable
2. yarn install
3. yarn config set enableTelemetry 0 to disable Yarn 4 telemetry[2] – I continue to believe we have no business broadcasting information about how we use the tools
4. Add the non-zero-install recommended gitignore entries (non-zero-install to not store the package cache in the repository, at least for now)[3]

[1] https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern
[2] https://yarnpkg.com/advanced/telemetry
[3] https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

### CODE REVIEW

**Comment by jstasiak** [comment]
#1109 should unblock the build here

**Review by raguiar9080 — APPROVED** [review]

**Comment by jstasiak** [comment]
Oops, I forgot to modify `.gitignore`, I'll do that now.

**Comment by jstasiak** [comment]
@raguiar9080 I forgot to disable Yarn telemetry earlier, I updated the patch to include that now and the description reflects it.

**Pull request merged**
