### PR TITLE
[TESTING] Make sidebar wider

### PR DESCRIPTION
**Pull request by rbruggem**
The default width 250px.
With a width of 400px, everything fits.

### CODE REVIEW

**Comment by rbruggem** [comment]
What do you think?
Better/worst?

**Comment by jstasiak** [comment]
At least on my 14" display the status quo looks much better to me than the new one

**Review by raguiar9080 — APPROVED** [review]
Same for me, I like it and makes the sidebar easier to read imo 👍

**Comment by rbruggem** [comment]
> Same for me, I like it and makes the sidebar easier to read imo 👍

the current sidebar in docs.lune.co ?

**Comment by raguiar9080** [comment]
Oh I misread what Jakub said 🙏 . For me, this change looks good since it makes everything on the sidebar one line which I prefer in terms of readability. I'm on a very big screen though.

**Comment by rbruggem** [comment]
I have to agree with @jstasiak . On 14 inch screens, it does not look good.

**Pull request closed without merging**
